/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/button.vue')['default']
    ComboBox: typeof import('./src/components/comboBox.vue')['default']
    Dialog: typeof import('./src/components/dialog.vue')['default']
    Form: typeof import('./src/components/form.vue')['default']
    TravelCard: typeof import('./src/components/travelCard.vue')['default']
  }
}
